2022-06-04 15:47:43,815 ERROR: Exception on /admin/form1/save [POST] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'admin.save_log' did not return a valid response. The function either returned None or ended without a return statement.
2022-06-04 15:51:21,373 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:51:29,527 ERROR: Exception on /admin/form1/save [POST] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'admin.save_log' did not return a valid response. The function either returned None or ended without a return statement.
2022-06-04 15:53:14,178 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:53:18,232 ERROR: Exception on /admin/form1/save [POST] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'admin.save_log' did not return a valid response. The function either returned None or ended without a return statement.
2022-06-04 15:54:12,288 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:54:20,723 ERROR: Exception on /admin/form1/save [POST] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'admin.save_log' did not return a valid response. The function either returned None or ended without a return statement.
2022-06-04 15:55:41,152 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:55:44,628 ERROR: Exception on /admin/form1/save [POST] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'admin.save_log' did not return a valid response. The function either returned None or ended without a return statement.
2022-06-04 15:56:05,522 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:56:23,047 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:57:08,550 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:57:12,308 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:58:49,203 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 16:00:50,599 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 16:01:23,026 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 16:02:17,479 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 16:04:43,619 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 16:09:49,266 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 16:10:51,634 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 16:12:23,576 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 16:12:29,089 ERROR: Exception on /admin/form1/save [POST] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ulrik/Git/Logger/app/admin/routes.py", line 52, in save_log
    message = request.form()
TypeError: 'ImmutableMultiDict' object is not callable
2022-06-04 16:12:54,385 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 16:13:14,328 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 16:13:25,079 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 16:13:49,285 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 16:14:07,069 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 16:14:57,101 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 16:14:57,897 ERROR: Exception on /admin/form1/save [POST] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ulrik/Git/Logger/app/admin/routes.py", line 52, in save_log
    message = request.form.get('message').getlist('newFields[]')
AttributeError: 'str' object has no attribute 'getlist'
2022-06-04 16:16:19,041 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 16:16:25,601 ERROR: Exception on /admin/form1/save [POST] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ulrik/Git/Logger/app/admin/routes.py", line 52, in save_log
    message = request.args.getlist['newFields()']
TypeError: 'method' object is not subscriptable
2022-06-04 16:16:47,039 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
