2022-05-29 01:47:24,140 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:31]
2022-05-29 01:48:01,232 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:31]
2022-05-29 01:49:26,093 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:31]
2022-05-29 01:49:47,722 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:31]
2022-06-01 19:42:22,090 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:33]
2022-06-01 19:42:34,897 ERROR: Exception on /login [POST] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ulrik/Git/Logger/app/routes.py", line 36, in login
    login_user(user, remember=form.remember_me.data)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_login/utils.py", line 196, in login_user
    user_id = getattr(user, current_app.login_manager.id_attribute)()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_user/user_mixin.py", line 23, in get_id
    user_manager = current_app.user_manager
AttributeError: 'Flask' object has no attribute 'user_manager'
2022-06-01 19:43:10,184 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:33]
2022-06-01 20:02:44,083 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:33]
2022-06-01 21:05:46,194 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:33]
2022-06-01 21:05:49,546 ERROR: Exception on /control_panel [GET] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_user/decorators.py", line 129, in decorator
    user_manager = current_app.user_manager
AttributeError: 'Flask' object has no attribute 'user_manager'
2022-06-01 21:06:21,161 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:33]
2022-06-01 21:59:11,989 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:33]
2022-06-02 00:56:07,933 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:36]
2022-06-02 00:57:03,969 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:36]
2022-06-02 00:57:23,789 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:36]
2022-06-02 00:57:41,916 ERROR: Exception on /user/sign-in [POST] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_user/user_manager.py", line 416, in login_stub
    return self.login_view()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_user/user_manager__views.py", line 379, in login_view
    if request.method == 'POST' and login_form.validate():
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_user/forms.py", line 201, in validate
    if user and user_manager.verify_password(self.password.data, user.password):
AttributeError: 'User' object has no attribute 'password'
2022-06-02 00:59:34,651 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:36]
2022-06-02 00:59:40,521 ERROR: Exception on /user/sign-in [POST] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_user/user_manager.py", line 416, in login_stub
    return self.login_view()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_user/user_manager__views.py", line 379, in login_view
    if request.method == 'POST' and login_form.validate():
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_user/forms.py", line 201, in validate
    if user and user_manager.verify_password(self.password.data, user.password):
AttributeError: 'User' object has no attribute 'password'
2022-06-02 01:00:10,243 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:36]
2022-06-02 01:00:20,474 ERROR: Exception on /user/sign-in [POST] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_user/user_manager.py", line 416, in login_stub
    return self.login_view()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_user/user_manager__views.py", line 379, in login_view
    if request.method == 'POST' and login_form.validate():
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_user/forms.py", line 201, in validate
    if user and user_manager.verify_password(self.password.data, user.password):
AttributeError: 'User' object has no attribute 'password'
2022-06-02 01:50:31,497 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:36]
2022-06-02 02:02:53,828 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:48]
2022-06-02 02:06:50,336 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:48]
2022-06-02 02:06:50,341 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:48]
2022-06-02 02:06:50,341 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:48]
2022-06-02 02:08:33,240 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:48]
2022-06-02 02:09:59,740 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:48]
2022-06-02 02:11:45,898 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:48]
